### ISSUE TITLE
Addon ohne Version Angabe definieren

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/nv_defaultaddons#1]
Es wäre sicher gut, wenn die Versionsangabe nur optional wäre.
Ich möchte z. B. Von einigen Addons immer gleich die aktuelle Version installiert haben.

**Comment by novinet-dsteffen** [comment]
leider verlangt die methode downloadAddon die Angabe einer Version

**Comment by novinet-dsteffen** [comment]
Ah ging doch, Update 1.1 ist draußen!
