### ISSUE TITLE
Fehler mit redaxo 5.17 und PHP 8.3

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/nv_defaultaddons#10]
In der Datei lib/class.nvDefaultAddons.php Zeile 65 muss getauscht werden:

            rex_install::downloadAddon($sPackage, $sVersion);
durch
 
      $rex_install = new rex_install();
           $rex_install->downloadAddon($sPackage, $sVersion);

Auf dem Tab Konfiguration erscheint oben noch diese Meldung, scheint die Funktionalität jedoch nicht zu beeinflussen:

Deprecated: Creation of dynamic property nvDefaultAddons::$addon is deprecated in redaxo/src/addons/nv_defaultaddons/lib/class.nvDefaultAddons.php on line 8

**Comment by AWqxKAWERbXo** [comment]
Kann ich bestätigen. Der Fix löst das Problem, dass kein Addon installiert werden kann.

**Comment by AWqxKAWERbXo** [comment]
gelöst in https://github.com/FriendsOfREDAXO/nv_defaultaddons/commit/693a2bf626fa8cafd2411da3ec74326e1ccb42c6
