### ISSUE TITLE
Rebranding zu default_addons

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/nv_defaultaddons#14]
**Feature description / Feature Beschreibung**

- [x] Letzte Version als `nv_defaultaddons` veröffentlichen mit Hinweis auf Migration zu FOR @alxndr-w 
- [x] Dazu muss der Key noch an FOR übertragen werden, ist dir das möglich @skerbis 
- [x] Änderungen in package.yml durchführen und Repository auf GitHub ändern @alxndr-w 
- [x] Neuen key `default_addons` anlegen. @skerbis wäre dir das möglich?
- [x] Installer-Action hinzufügen

**Comment by skerbis** [comment]
was von beiden hättest du denn nun gerne?

**Comment by skerbis** [comment]
erledigt

**Comment by AWqxKAWERbXo** [comment]
Merci.
