### ISSUE TITLE
Fehler: Deprecated: Non-static method...

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/nv_defaultaddons#2]
Deprecated: Non-static method nvDefaultAddons::getProjectAddons() should not be called statically in redaxo/src/addons/nv_defaultaddons/pages/install.php on line 3

![image](https://user-images.githubusercontent.com/330516/88161331-275a6500-cc10-11ea-8fa5-fcd9fdef1425.png)

**Comment by AWqxKAWERbXo** [comment]
@olien möchtest du das noch fixen?
