### ISSUE TITLE
Fehler die Zweite...

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/nv_defaultaddons#3]
![image](https://user-images.githubusercontent.com/330516/88161671-9041dd00-cc10-11ea-8445-e5202e9928c4.png)

**Comment by AWqxKAWERbXo** [comment]
duplicate #10

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/nv_defaultaddons/commit/693a2bf626fa8cafd2411da3ec74326e1ccb42c6
