### ISSUE TITLE
Idee: Config Seite mit der Möglichkeit einen eigenen Pfad zur .json Datei anzugeben

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/nv_defaultaddons#4]
Dann könnte man die Datei im Projekt / Theme Ordner mitschleifen :-))

**Comment by novinet-dsteffen** [comment]
Ich habe es jetzt anders gelöst: es gibt eine Konfigurations-Seite, über die können die Addons in JSON-Notation einfach reinkopiert werden. -> v1.2
