### ISSUE TITLE
Deprecated: Non-static method nvDefaultAddons::getProjectAddons() should not be called statically

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/nv_defaultaddons#7]
![image](https://user-images.githubusercontent.com/330516/149908142-25a7195b-492b-4cb1-a3f8-88c6cb7364d6.png)

REX Aktuell, PHP 7.4.21

**Comment by novinet-git** [comment]
Version 1.2.1 ist draussen und sollte das beheben

**Comment by olien** [comment]
Danke
