### ISSUE TITLE
Fehler bei Installation

### ISSUE THREAD

**Issue by rotzek** [FriendsOfREDAXO/nv_defaultaddons#9]
Error
Non-static method rex_install::downloadAddon() cannot be called statically
redaxo/src/addons/nv_defaultaddons/lib/class.nvDefaultAddons.php

Error thrown with message "Non-static method rex_install::downloadAddon() cannot be called statically"

**Comment by AWqxKAWERbXo** [comment]
duplicate #10

**Comment by AWqxKAWERbXo** [comment]
gelöst in https://github.com/FriendsOfREDAXO/nv_defaultaddons/commit/693a2bf626fa8cafd2411da3ec74326e1ccb42c6
